site_name: cherno-cpp-notes
docs_dir: docs/
repo_name: 'Nagi-ovo/Cherno-CPP-Notes'
repo_url: https://github.com/Nagi-ovo/Cherno-CPP-Notes
theme:
  name: material
  language: zh
  static_templates:
    - 404.html
  include_search_page: false
  search_index_only: true
  features:
    - header.autohide
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate
  palette:
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: deep blue
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: cyan
      accent: deep blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

extra_javascript:
  - javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

nav:
  - 前言: 'README.md'
  - 05 C++是怎样工作的: '1-50/05 How C++ Works.md'
  - 06 C++编译器是如何工作的: '1-50/06 How the C++ Compiler Works.md'
  - 07 C++链接器是如何工作的: '1-50/07 How the C++ Linker Works.md'
  - 08 C++中的变量: '1-50/08 Variables in C++.md'
  - 09 C++中的函数: '1-50/09 Functions in C++.md'
  - 10 C++中的头文件: '1-50/10 C++ Header Files.md'
  - 11 如何在Visual Studio中调试: '1-50/11 How to DEBUG C++ in Visual Studio.md'
  - 12 C++条件与分支(if语句): '1-50/12 CONDITIONS and BRANCHES in C++.md'
  - 13 Visual Studio的最佳设置: '1-50/13  BEST Visual Studio Setup for C++ Projects!.md'
  - 14 C++循环(for&while): '1-50/14 Loops in C++(for,while loops).md'
  - 15 C++控制流语句: '1-50/15 Control Flows in C++(continue,break,return).md'
  - 16 C++指针: '1-50/16 POINTERS in C++.md'
  - 17 C++引用: '1-50/17 REFERENCES in C++.md'
  - 18 C++类: '1-50/18 CLASSES in C++.md'
  - 19 C++类与结构体对比: '1-50/19 CLASSES vs STRUCTS in C++.md'
  - 20 如何写一个C++类: '1-50/20 How to Write a C++ Class.md'
  - 21 C++中的静态(static): '1-50/21 Static in C++.md'
  - 22 C++类和结构体中的静态(static): '1-50/22 Static for Classes and Structs in C++.md'
  - 23 C++中的局部静态(Local Static): '1-50/23 Local Static in C++.md'
  - 24 C++枚举: '1-50/24 ENUMS in C++.md'
  - 25 C++构造函数: '1-50/25 Constructors in C++.md'
  - 26 C++析构函数: '1-50/26 Destructors in C++.md'
  - 27 C++继承: '1-50/27 Inheritance in C++.md'
  - 28 C++虚函数: '1-50/28 Virtual Functions in C++.md'
  - 29 C++接口(纯虚函数): '1-50/29 Interfaces in C++ (Pure Virtual Functions).md'
  - 30 C++可见性: '1-50/29 Interfaces in C++ (Pure Virtual Functions).md'
  - 31 C++数组: '1-50/31 Arrays in C++.md'
  - 32 C++字符串: '1-50/32 How Strings Work in C++ (and how to use them).md'
  - 33 C++字符串字面量: '1-50/33 String Literals in C++.md'
  - 34 C++中的const: '1-50/34 CONST in C++.md'
  - 35 C++的mutable关键字: '1-50/35 The Mutable Keyword in C++.md'
  - 36 C++的成员初始化列表: '1-50/36  Member Initializer Lists in C++ (Constructor Initializer List).md'
  - 37 C++的三元操作符: '1-50/37 Ternary Operators in C++ (Conditional Assignment).md'
  - 38 创建并初始化C++对象: '1-50/38 How to CREATE_INSTANTIATE OBJECTS in C++.md'
  - 39 C++ new关键字: '1-50/39 The NEW Keyword in C++.md'
  - 40 C++隐式转换与explicit关键字: '1-50/40 Implicit Conversion and the Explicit Keyword in C++.md'
  - 41 C++运算符及其重载: '1-50/41 OPERATORS and OPERATOR OVERLOADING in C++.md'
  - 42 C++的this关键字: '1-50/42 The `this` keyword in C++.md'
  - 43 C++的对象生存期(栈作用域生存期): '1-50/43 Object Lifetime in C++ (Stack_Scope Lifetimes).md'
  - 44 C++的智能指针: '1-50/44 SMART POINTERS in C++.md'
  - 45 C++的复制与拷贝构造函数: '1-50/45 Copying and Copy Constructors in C++.md'
  - 46 C++的箭头操作符: '1-50/46 The Arrow Operator in C++.md'
  - 47 C++的动态数组(std::vector): '1-50/47 Dynamic Arrays in C++ (std - -vector).md'
  - 48 C++的std::vector使用优化: '1-50/48 Optimizing the usage of std - -vector in C++.md'
  - 49 C++中使用库（静态链接）: '1-50/49 Using Libraries in C++ (Static Linking).md'
  - 50 C++中使用动态库: '1-50/50 Using Dynamic Libraries in C++.md'
  - 51 C++中创建与使用库: '51-100/51 Making and Working with Libraries in C++ (Multiple Projects in VS).md'
  - 52 C++中如何处理多返回值: '51-100/52 How to Deal with Multiple Return Values in C++.md'
  - 53 C++的模板: '51-100/53 Templates in C++.md'
  - 54 C++的堆与栈内存的比较: '51-100/54 Stack vs Heap Memory in C++.md'
  - 55 C++的宏: '51-100/55 Macros in C++.md'
  - 56 C++的auto关键字: '51-100/56 The `auto` keyword in C++.md'
  - 57 C++的静态数组(std array): '51-100/57 Static Arrays in C++ (std - -array).md'
  - 58 C++的函数指针: '51-100/58 Function Pointers in C++.md'
  - 59 C++的lambda: '51-100/59 Lambdas in C++.md'
  - 60 为什么不使用namespace::std: '51-100/60 Why I don't `using namespace std`.md'
  - 61 C++的名称空间: '51-100/61 Namespaces in C++.md'
  - 62 C++的线程: '51-100/62 Threads in C++.md'
  - 63 C++的计时: '51-100/63 Timing in C++.md'
  - 64 C++多维数组: '51-100/64 Multidimensional Arrays in C++ (2D arrays).md'
  - 65 C++的排序: '51-100/65 Sorting in C++.md'
  - 66 C++的类型双关: '51-100/66 Type Punning in C++.md'
  - 67 C++的联合体: '51-100/67 Unions in C++.md'
  - 68 C++的虚析构函数: '51-100/68 Virtual Destructors in C++.md'
  - 69 C++的类型转换: '51-100/69 Casting in C++.md'
  - 70 条件与操作断点: '51-100/70 Conditional and Action Breakpoints in C++.md'
  - 71 现代C++中的安全以及如何教授(作者个人观点): '51-100/71 Safety in modern C++ and how to teach it.md'
  - 72 C++的预编译头文件: '51-100/72 Precompiled Headers in C++.md'
  - 73 C++的dynamic_cast: '51-100/73 Dynamic Casting in C++.md'
  - 74 C++的基准测试: '51-100/74 BENCHMARKING in C++ (how to measure performance).md'
  - 75 C++的结构化绑定: '51-100/75 STRUCTURED BINDINGS in C++.md'
  - 76 如何处理OPTIONAL数据: '51-100/76 How to Deal with OPTIONAL Data in C++.md'
  - 77 单一变量存放多类型的数据: '51-100/77 Multiple TYPES of Data in a SINGLE VARIABLE in C++.md'
  - 78 如何存储任意类型的数据: '51-100/78 How to store ANY data in C++.md'
  - 79 如何让C++运行得更快: '51-100/79 How to make C++ run FASTER (with std-async).md'
  - 80 如何让C++字符串更快: '51-100/80 How to make your STRINGS faster.md'
  - 81 C++的可视化基准测试: '51-100/81 VISUAL BENCHMARKING in C++.md'
  - 82 C++的单例模式: '51-100/82 SINGLETONS in C++.md'
  - 83 C++的小字符串优化: '51-100/83 Small String Optimization in C++.md'
  - 84 跟踪内存分配的简单方法: '51-100/84 Track MEMORY ALLOCATIONS the Easy way in C++.md'
  - 85 C++的左值与右值: '51-100/85 lvalues and rvalues in C++.md'
  - 86 C++持续集成: '51-100/86 Continuous Integration in C++.md'
  - 87 C++ 静态分析: '51-100/87 Static Analysis in C++.md'
  - 88 C++的参数计算顺序: '51-100/88 Argument Evaluation Order in C++.md'
  - 89 C++移动语义: '51-100/89 Move Semantics in C++.md'
  - 90 std::move与移动赋值操作符: '51-100/90 std--move and the Move Assignment Operator in C++.md'
